module.exports = {
    traverseItem: [
        "__root__",
        "config1",
        "div10",
        "div11",
        "div21",
        "div31",
        "div41",
        "div13",
        "v_section_empty",
        "v_json",
        "v_array",
        "v_string",
        "v_text",
        "v_email",
        "v_date",
        "v_time",
        "v_datetime",
        "v_number",
        "v_int",
        "v_float",
        "v_money",
        "v_boolean",
        "config-2",
        "div21",
        "div22",
        "c0_s0",
        "c1_s0",
        "config 3",
        "div31",
        "div32"
    ],
    traverseValue: [
        3,
        3,
        1,
        1,
        1,
        14,
        4,
        2
    ],
    traverseProperty: [
        "div10 / string",
        "div41 / string",
        "v_json / json",
        "v_array / array",
        "v_string / string",
        "v_text / text",
        "v_email / email",
        "v_date / date",
        "v_time / time",
        "v_datetime / datetime",
        "v_number / number",
        "v_int / int",
        "v_float / float",
        "v_money / money",
        "v_boolean / boolean",
        "div21 / array",
        "div22 / array",
        "c0_s0 / string",
        "c1_s0 / string",
        "div31 / string",
        "div32 / string"
    ]
};
